"""requirement body, is_common, case_sensitive, salary_period

명세 4장 "스키마 변경 이력" 반영.

    posting_skill.requirement   3값 → 4값 (body 추가)
    skill.is_common             전 직군 공통 도구 플래그
    skill_alias.case_sensitive  대소문자 구분 매칭
    job_posting.salary_period   annual · monthly · hourly

★ 이 마이그레이션 직후 반드시 전체 reparse 를 돌려야 한다.
  기존 행의 body 는 preferred 로 이미 뭉개져 있어 SQL 로는 되돌릴 수 없고,
  description 에서 재추출해야만 복원된다.

      alembic upgrade head
      python -m scripts.seed_skills
      python -m app.cli reparse        ← 생략 금지

Revision ID: 8b80cea40590
Revises: 3e23078a364f
Create Date: 2026-07-30 16:31:05.201275
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8b80cea40590"
down_revision: str | None = "3e23078a364f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_posting",
        sa.Column("salary_period", sa.String(length=8), nullable=True),
        schema="market",
    )
    op.add_column(
        "skill",
        sa.Column("is_common", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="market",
    )
    op.add_column(
        "skill_alias",
        sa.Column("case_sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="market",
    )
    # ### end Alembic commands ###

    # ── 수동: CHECK 제약 (alembic autogenerate 는 CHECK 를 비교하지 않는다) ──
    op.drop_constraint(
        "posting_skill_requirement_chk", "posting_skill", schema="market", type_="check"
    )
    op.create_check_constraint(
        "posting_skill_requirement_chk",
        "posting_skill",
        "requirement IN ('required', 'preferred', 'tag', 'body')",
        schema="market",
    )
    op.create_check_constraint(
        "job_posting_salary_period_chk",
        "job_posting",
        "salary_period IS NULL OR salary_period IN ('annual', 'monthly', 'hourly')",
        schema="market",
    )


def downgrade() -> None:
    # body 등급 행을 preferred 로 되돌린 뒤에야 3값 제약을 걸 수 있다.
    # (되돌린 값은 복구되지 않는다 — 다시 올릴 때 reparse 가 필요한 이유다)
    op.execute(
        "UPDATE market.posting_skill SET requirement = 'preferred' WHERE requirement = 'body'"
    )
    op.drop_constraint(
        "job_posting_salary_period_chk", "job_posting", schema="market", type_="check"
    )
    op.drop_constraint(
        "posting_skill_requirement_chk", "posting_skill", schema="market", type_="check"
    )
    op.create_check_constraint(
        "posting_skill_requirement_chk",
        "posting_skill",
        "requirement IN ('required', 'preferred', 'tag')",
        schema="market",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skill_alias", "case_sensitive", schema="market")
    op.drop_column("skill", "is_common", schema="market")
    op.drop_column("job_posting", "salary_period", schema="market")
    # ### end Alembic commands ###
