"""baseline schema

Revision ID: 6e3c0e6b14ca
Revises:
Create Date: 2026-07-30 15:14:22.475089
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6e3c0e6b14ca"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ── ORM 이 모르는 객체 (수동 관리) ──────────────────────────────────────────
# extension · schema 는 init.sql 이 만든다. 여기서는 트리거와 seed 만 다룬다.

TOUCH_FN = """
CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

# updated_at 을 가진 테이블만
TOUCH_TABLES = [
    ("market", "company"),
    ("market", "job_posting"),
    ("market", "skill"),
    ("chat", "chat_session"),
]

# enums.TechField 와 code 가 1:1 이어야 한다.
TECH_FIELDS = [
    ("backend", "백엔드", 10),
    ("frontend", "프론트엔드", 20),
    ("android", "안드로이드", 30),
    ("ios", "iOS", 40),
    ("data", "데이터", 50),
    ("devops", "DevOps/인프라", 60),
    ("ai", "AI/ML", 70),
    ("etc", "기타", 99),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_session",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="chat",
    )
    op.create_index(
        "chat_session_user_idx",
        "chat_session",
        ["user_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        schema="chat",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "company",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name_key", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("business_content", sa.Text(), nullable=True),
        sa.Column("talent_profile", sa.Text(), nullable=True),
        sa.Column(
            "size_type", sa.String(length=20), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("industry", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("founded", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("revenue", sa.BigInteger(), nullable=True),
        sa.Column("homepage", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("profile_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embed_hash", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "raw_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_type IN ('startup', 'small', 'medium', 'large', 'enterprise', 'unknown')",
            name="company_size_type_chk",
        ),
        sa.CheckConstraint(
            "employee_count IS NULL OR employee_count >= 0", name="company_employee_count_chk"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_key"),
        schema="market",
    )
    op.create_index(
        "company_embed_todo_idx",
        "company",
        ["id"],
        unique=False,
        schema="market",
        postgresql_where=sa.text("profile_embedding IS NULL"),
    )
    op.create_index(
        "company_name_trgm_idx",
        "company",
        ["name"],
        unique=False,
        schema="market",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "company_profile_embedding_idx",
        "company",
        ["profile_embedding"],
        unique=False,
        schema="market",
        postgresql_using="hnsw",
        postgresql_ops={"profile_embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index(
        "company_size_type_idx", "company", ["size_type"], unique=False, schema="market"
    )
    op.create_table(
        "crawl_run",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inserted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("embedded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('crawl', 'embed')", name="crawl_run_kind_chk"),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'partial', 'failed')", name="crawl_run_status_chk"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="market",
    )
    op.create_index(
        "crawl_run_kind_started_idx",
        "crawl_run",
        ["kind", sa.literal_column("started_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_index(
        "crawl_run_source_started_idx",
        "crawl_run",
        ["source", sa.literal_column("started_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("is_ambiguous", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="market",
    )
    op.create_table(
        "tech_field",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="market",
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system', 'tool')", name="chat_message_role_chk"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["chat.chat_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "seq", name="chat_message_uk"),
        schema="chat",
    )
    op.create_table(
        "company_source",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "source_company_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('saramin', 'jobkorea', 'wanted', 'jumpit')",
            name="company_source_source_chk",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["market.company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_company_id", name="company_source_uk"),
        schema="market",
    )
    op.create_index(
        "company_source_company_idx",
        "company_source",
        ["company_id"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "job_posting",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_job_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("field_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("company_name_raw", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "tags_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("career_min", sa.Integer(), nullable=True),
        sa.Column("career_max", sa.Integer(), nullable=True),
        sa.Column("employment_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
        sa.Column("education", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("welfare", sa.Text(), nullable=True),
        sa.Column("salary_raw", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column(
            "salary_type", sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column("body_is_image", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("embed_hash", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "raw_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "salary_type IN ('range', 'min_only', 'max_only', 'negotiable', 'unknown')",
            name="job_posting_salary_type_chk",
        ),
        sa.CheckConstraint(
            "source IN ('saramin', 'jobkorea', 'wanted', 'jumpit')", name="job_posting_source_chk"
        ),
        sa.CheckConstraint(
            "career_min IS NULL OR career_max IS NULL OR career_min <= career_max",
            name="job_posting_career_chk",
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name="job_posting_salary_chk",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["market.company.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["field_id"], ["market.tech_field.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_job_id", name="job_posting_uk"),
        schema="market",
    )
    op.create_index(
        "job_posting_career_idx",
        "job_posting",
        ["career_min", "career_max"],
        unique=False,
        schema="market",
    )
    op.create_index(
        "job_posting_collected_idx",
        "job_posting",
        [sa.literal_column("collected_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_index(
        "job_posting_company_idx", "job_posting", ["company_id"], unique=False, schema="market"
    )
    op.create_index(
        "job_posting_embed_todo_idx",
        "job_posting",
        ["id"],
        unique=False,
        schema="market",
        postgresql_where=sa.text(
            "body_is_image = false AND description IS NOT NULL AND (embed_hash IS NULL OR embed_hash IS DISTINCT FROM content_hash)"
        ),
    )
    op.create_index(
        "job_posting_field_posted_idx",
        "job_posting",
        ["field_id", sa.literal_column("posted_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_index(
        "job_posting_location_idx", "job_posting", ["location"], unique=False, schema="market"
    )
    op.create_index(
        "job_posting_posted_idx",
        "job_posting",
        [sa.literal_column("posted_at DESC")],
        unique=False,
        schema="market",
    )
    op.create_index(
        "job_posting_salary_idx",
        "job_posting",
        ["field_id", "salary_min", "salary_max"],
        unique=False,
        schema="market",
        postgresql_where=sa.text("salary_type IN ('range', 'min_only', 'max_only')"),
    )
    op.create_table(
        "skill_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["market.skill.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        schema="market",
    )
    op.create_index(
        "skill_alias_skill_idx", "skill_alias", ["skill_id"], unique=False, schema="market"
    )
    op.create_table(
        "skill_field",
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["market.tech_field.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["market.skill.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("skill_id", "field_id"),
        schema="market",
    )
    op.create_index(
        "skill_field_field_idx", "skill_field", ["field_id"], unique=False, schema="market"
    )
    op.create_table(
        "chat_tool_call",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("chart_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["chat.chat_message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="chat",
    )
    op.create_index(
        "chat_tool_call_message_idx",
        "chat_tool_call",
        ["message_id", "seq"],
        unique=False,
        schema="chat",
    )
    op.create_index(
        "chat_tool_call_tool_idx",
        "chat_tool_call",
        ["tool_name", sa.literal_column("created_at DESC")],
        unique=False,
        schema="chat",
    )
    op.create_table(
        "posting_chunk",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("posting_id", sa.BigInteger(), nullable=False),
        sa.Column("section", sa.String(length=20), nullable=False),
        sa.Column("seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "section IN ('responsibility', 'required', 'preferred')",
            name="posting_chunk_section_chk",
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["market.job_posting.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("posting_id", "section", "seq", name="posting_chunk_uk"),
        schema="market",
    )
    op.create_index(
        "posting_chunk_embedding_idx",
        "posting_chunk",
        ["embedding"],
        unique=False,
        schema="market",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index(
        "posting_chunk_section_idx", "posting_chunk", ["section"], unique=False, schema="market"
    )
    op.create_table(
        "posting_skill",
        sa.Column("posting_id", sa.BigInteger(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("requirement", sa.String(length=16), nullable=False),
        sa.Column("mentions", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "requirement IN ('required', 'preferred', 'tag')", name="posting_skill_requirement_chk"
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["market.job_posting.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["market.skill.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("posting_id", "skill_id"),
        schema="market",
    )
    op.create_index(
        "posting_skill_skill_idx",
        "posting_skill",
        ["skill_id", "requirement"],
        unique=False,
        schema="market",
    )
    # ### end Alembic commands ###

    # ── 수동: updated_at 트리거 ────────────────────────────────────────────
    op.execute(TOUCH_FN)
    for schema, table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_touch BEFORE UPDATE ON {schema}.{table} "
            f"FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at()"
        )

    # ── 수동: tech_field seed ──────────────────────────────────────────────
    values = ", ".join(f"('{code}', '{name}', {order})" for code, name, order in TECH_FIELDS)
    op.execute(
        f"INSERT INTO market.tech_field (code, name, sort_order) VALUES {values} "
        "ON CONFLICT (code) DO NOTHING"
    )


def downgrade() -> None:
    # ── 수동 객체부터 되돌린다 ────────────────────────────────────────────
    for schema, table in TOUCH_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_touch ON {schema}.{table}")
    op.execute("DROP FUNCTION IF EXISTS public.touch_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("posting_skill_skill_idx", table_name="posting_skill", schema="market")
    op.drop_table("posting_skill", schema="market")
    op.drop_index("posting_chunk_section_idx", table_name="posting_chunk", schema="market")
    op.drop_index(
        "posting_chunk_embedding_idx",
        table_name="posting_chunk",
        schema="market",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_table("posting_chunk", schema="market")
    op.drop_index("chat_tool_call_tool_idx", table_name="chat_tool_call", schema="chat")
    op.drop_index("chat_tool_call_message_idx", table_name="chat_tool_call", schema="chat")
    op.drop_table("chat_tool_call", schema="chat")
    op.drop_index("skill_field_field_idx", table_name="skill_field", schema="market")
    op.drop_table("skill_field", schema="market")
    op.drop_index("skill_alias_skill_idx", table_name="skill_alias", schema="market")
    op.drop_table("skill_alias", schema="market")
    op.drop_index(
        "job_posting_salary_idx",
        table_name="job_posting",
        schema="market",
        postgresql_where=sa.text("salary_type IN ('range', 'min_only', 'max_only')"),
    )
    op.drop_index("job_posting_posted_idx", table_name="job_posting", schema="market")
    op.drop_index("job_posting_location_idx", table_name="job_posting", schema="market")
    op.drop_index("job_posting_field_posted_idx", table_name="job_posting", schema="market")
    op.drop_index(
        "job_posting_embed_todo_idx",
        table_name="job_posting",
        schema="market",
        postgresql_where=sa.text(
            "body_is_image = false AND description IS NOT NULL AND (embed_hash IS NULL OR embed_hash IS DISTINCT FROM content_hash)"
        ),
    )
    op.drop_index("job_posting_company_idx", table_name="job_posting", schema="market")
    op.drop_index("job_posting_collected_idx", table_name="job_posting", schema="market")
    op.drop_index("job_posting_career_idx", table_name="job_posting", schema="market")
    op.drop_table("job_posting", schema="market")
    op.drop_index("company_source_company_idx", table_name="company_source", schema="market")
    op.drop_table("company_source", schema="market")
    op.drop_table("chat_message", schema="chat")
    op.drop_table("tech_field", schema="market")
    op.drop_table("skill", schema="market")
    op.drop_index("crawl_run_source_started_idx", table_name="crawl_run", schema="market")
    op.drop_index("crawl_run_kind_started_idx", table_name="crawl_run", schema="market")
    op.drop_table("crawl_run", schema="market")
    op.drop_index("company_size_type_idx", table_name="company", schema="market")
    op.drop_index(
        "company_profile_embedding_idx",
        table_name="company",
        schema="market",
        postgresql_using="hnsw",
        postgresql_ops={"profile_embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_index(
        "company_name_trgm_idx",
        table_name="company",
        schema="market",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "company_embed_todo_idx",
        table_name="company",
        schema="market",
        postgresql_where=sa.text("profile_embedding IS NULL"),
    )
    op.drop_table("company", schema="market")
    op.drop_index(
        "chat_session_user_idx",
        table_name="chat_session",
        schema="chat",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("chat_session", schema="chat")
    # ### end Alembic commands ###
