"""body extract failed flag

Revision ID: 01bed769534d
Revises: 8b80cea40590
Create Date: 2026-07-30 18:47:43.220654
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "01bed769534d"
down_revision: str | None = "8b80cea40590"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_posting",
        sa.Column(
            "body_extract_failed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        schema="market",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_posting", "body_extract_failed", schema="market")
    # ### end Alembic commands ###
